GET https://www.wikipedia.org/

###

GET https://reqres.in/api/users/2 HTTP/1.1
Host: reqres.in


###
POST https://reqres.in/api/users HTTP/1.1
Host: reqres.in
Content-Type: application/json

{
  "name": "morpheus",
  "job": "leader"
}

###
GET localhost:8000/hello
Content-Type: application/json

###
POST localhost:8000/data
Content-Type: application/json

{
  "name": "morpheus",
  "job": "leader"
}

###
PUT localhost:8000/update
Content-Type: application/json

{
  "name": "morpheus",
  "job": "tester"
}

###
GET localhost:8080/home


###
POST localhost:8080
Content-Type: application/json

{
  "name": "Alice"
}


###
GET localhost:8000/hello

###
POST localhost:8000/user
Content-Type: application/json


{
  "name": "John",
  "age": 30,
  "email": "john@example.com",
  "status": "processing"
}

###
PUT localhost:8000/user
Content-Type: application/json

{
  "status": "ready"
}

###
PATCH localhost:8000/user
Content-Type: application/json

{
  "status": "active"
}


